### ISSUE TITLE
update of swagger docs

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#16]
not urgent but could do with updating the API docs at http://api.openassistive.org/docs/v1/

leave till we have finished the other tasks

**Comment by hosseinzoda** [comment]
There's nothing to add yet. maybe few fix on details. I'll leave it for later.

**Comment by willwade** [comment]
Have we got any more endpoints? I guess not. When I wrote this I realised the save won't work due to recaptcha addition. It's not urgent as you say.

**Comment by hosseinzoda** [comment]
Did an update.
