### ISSUE TITLE
bug: adding a project of same name

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#18]
Hmm. This is tricky.

Try adding: https://github.com/ipomoena/dasher

it adds the image and thumb but of course not the md file. This is because, I'm guessing, a conflict of short_name (i.e. with https://openassistive.org/item/dasher/). Right?

What should happen: It gets highlighted as a duplicate to the front_end (or is there something else going wrong?)

**Comment by hosseinzoda** [comment]
I think there's some bug in savejson. I need to track it down.

**Comment by willwade** [comment]
Not sure if this is the best place to leave this... Its all the items that are in /items that are on source forge that we could with updating (and led to me discovering this bug)

http://sourceforge.net/projects/amis
https://sourceforge.net/projects/espeak/
http://sourceforge.net/projects/gameaccess
https://sourceforge.net/projects/magnifier/
http://sourceforge.net/projects/tuxpaint
http://sourceforge.net/projects/sviacam/ 
http://sourceforge.net/projects/sawat/
http://sourceforge.net/projects/sayzme/
http://sourceforge.net/projects/powertalk/
https://sourceforge.net/projects/freespeech/
https://sourceforge.net/projects/opendisc
https://sourceforge.net/projects/numnavigator/
http://sourceforge.net/projects/myftc/
http://sourceforge.net/projects/gameaccess
http://sourceforge.net/projects/eviacam/
http://sourceforge.net/projects/emacspeak/
http://sourceforge.net/projects/uncbats
http://sourceforge.net/projects/uncassist

**Comment by hosseinzoda** [comment]
@willwade I think It's time to modify how commits to github work.
Currently there are three commits at every add.
We need to change it. It will also help issue #10 

Okay this is what I'm thinking.

`hubfs` module has read/write to a single file. with [octokat](https://www.npmjs.com/package/octokat) which `hubfs` is using it we can write multiple files in single commit, mentioned in here. https://github.com/philschatz/octokat.js/issues/97#issuecomment-194455401

This may or may not be related to this issue. Changing gihub write feature will effect this error. it should get fixed.

What do you think?

**Comment by willwade** [comment]
Yep. Makes sense. Do it ;)

**Comment by hosseinzoda** [comment]
Closed for now
