### ISSUE TITLE
Duplicate finder not working

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#22]
Optikey (https://github.com/OptiKey/OptiKey) is now in the un-moderated list three times: https://openassistive.org/tags/un-moderated/

Whats happening:

- People are adding https://github.com/OptiKey/OptiKey to the add feature of the site
- Its not coming back as already existing

What should happen:

- It should say that there is a possible duplicate. Its currently un-moderated. Please wait till someone moderates it

**Comment by hosseinzoda** [comment]
Other than keeping track of un-moderated, Now search for item is done with `project_url` & `short_title`.
I did few tests with it. It needs more tests to make sure it's running as expected.
