### ISSUE TITLE
Dropbox URL

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#23]
I think I need to update the docs on Dropbox.  

Try adding https://www.dropbox.com/s/0hvuehs850qfcrg/SpeechDasher.md 

"Error Content has invalid format"

Whats killing it?

**Comment by hosseinzoda** [comment]
I see url format of dropbox has changed a bit. I will relax the rules to cover this too.

**Comment by hosseinzoda** [comment]
That fixed it. The url still needs `datemod` field. Maybe it's good to use `date` instead of it if not exists.

**Comment by willwade** [comment]
One small prob. Not liking original_url - (try https://www.dropbox.com/s/jgfi8orhvrmoc1h/toowheels.md?dl=0)

**Comment by hosseinzoda** [comment]
Fixed
