### ISSUE TITLE
code cleanup

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#24]
Because AWS lambda would be effectively free (rather than heroku). Im looking at getting it working on that (using [up](https://apex.github.io/up/) btw). In doing so I'm cleaning up some deprecated code.

Notably, I think the following can now be removed..

https://github.com/openassistive/OpenATBackend/blob/8e184e19d4b8f5fc4480feb8479a718ba8430fba/server.js#L16 to https://github.com/openassistive/OpenATBackend/blob/8e184e19d4b8f5fc4480feb8479a718ba8430fba/server.js#L24 I think is no longer needed (and mkdirp can be removed from package.json)

this whole file: https://github.com/openassistive/OpenATBackend/blob/master/js/git/git.controller.js
(I think made it in when I started doing the git stuff)

functions: https://github.com/openassistive/OpenATBackend/blob/8e184e19d4b8f5fc4480feb8479a718ba8430fba/js/functions.js#L258

https://github.com/openassistive/OpenATBackend/blob/8e184e19d4b8f5fc4480feb8479a718ba8430fba/js/functions.js#L288

https://github.com/openassistive/OpenATBackend/blob/8e184e19d4b8f5fc4480feb8479a718ba8430fba/js/functions.js#L338

https://github.com/openassistive/OpenATBackend/blob/8e184e19d4b8f5fc4480feb8479a718ba8430fba/js/functions.js#L361

And lastly - am I right in that we don't use this dir anymore? https://github.com/openassistive/OpenATBackend/tree/master/output 

Am I right? Any more?

**Comment by hosseinzoda** [comment]
"AWS lambda" is not good when there's no database to keep the data. Otherwise each time script loads  it should load `items_index.csv` from FrontEnd repo.
I think only `items_index.csv` is cached in memory. Maybe we need a solution for that.

**Comment by hosseinzoda** [comment]
About the other things i think you are right. 
Testing it is the simplest way to find out...
@willwade Do you run BackEnd in your machine when testing? Cause i made it easy for my self. I need to write how it's done `README.md` (for development). FrontEnd will listen to `localhost:5000` if it's running with `hugo server`. So they're connected.
Also it will not mess with master branch of FrontEnd (found it super helpful).

**Comment by willwade** [comment]
Yes. Well kind of - (I now use direnv to manage the env vars which helps) - but how are you changing the ip/port easily for the frontend and not committing directly to GitHub on testing?

Re: AWS_lambda - yeah - I did wonder that. I'm not too bothered - just figured it was time to get rid of some of that old code to be honest - notably the directory writing stuff.. Re: items_index.csv - hmmm - I guess reading/writing to that file on GitHub directly isn't a great idea (will force the server to rebuild for one - and also slow). Maybe not really a problem right now. Heroku is doing us fine to be honest..

**Comment by hosseinzoda** [comment]
Simple setup. Add env TEST_MODE=1 , Which makes use of `test` branch instead of `master`.
Only saving part uses `test`. That's all i guess.
```
#!/bin/sh

export GitHubOAuth=<key>
export PAPERTRAIL_API_TOKEN=<not sure what it is>
export RecaptchaSecret=<secret>
export AlgoliaAppID=<id>
export AlgoliaAPIKey=<key>
export OpenATIndexName=<name>
export TEST_MODE=1
```

**Comment by willwade** [comment]
Great. I’ll update the readme..  Thanks for that :)
