### ISSUE TITLE
Sourceforge down - move to rest API

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#27]
Can we move the scraper for sourceforge to their REST api?

E.g. https://sourceforge.net/rest/p/sawat/

( put /rest/p/ on the url)

https://sourceforge.net/p/forge/documentation/Allura%20API/

**Comment by hosseinzoda** [comment]
@willwade rest api output doesn't have project last update date.
but the original page still contains last update date. I can fix existing scrapper.

**Comment by hosseinzoda** [comment]
Fixed, I did combine rest and the existing scraper to get the most out of it.
