### ISSUE TITLE
Need to verify format of input before /save

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#3]
No checking being done yet. Needs to happen once format settles

**Comment by willwade** [comment]
https://github.com/openassistive/OpenATBackend/blob/master/js/savejson/savejson.controller.js#L11

**Comment by hosseinzoda** [comment]
Also we need to verify the user before updating if the record exists.
We can perform simple verification with email that project author has provided.

**Comment by willwade** [comment]
we actually don't have any user system at the moment. not sure how we would do this or even if there is a need

**Comment by hosseinzoda** [comment]
No need for user system. We can send an email with a code to author if it's not the first time submitting for save. Then they need to pass it at save.

**Comment by hosseinzoda** [comment]
Though there's no simple way to get author's email from the project.

**Comment by hosseinzoda** [comment]
verify with email is not going to work. User can edit content between "get" and "save" this is why invalid content can get in.

**Comment by willwade** [comment]
we can use cors to limit access to api from frontend. And on frontend maybe put a captcha? (just to limit spam)

**Comment by hosseinzoda** [comment]
Yeah. This is not very important right now. There are lots of ways to improve it.
We can ask for email from user for verifying them on next save.

**Comment by willwade** [comment]
Leaving this here for note: https://www.npmjs.com/package/validate (need schema of the openat scheme written and then we can validate against that easy enough)

**Comment by hosseinzoda** [comment]
Validation notes
```
title, short_title, authors = required string
description = required markdown string, Needs sanitization to prevent injecting scripts, iframes, etc
datemod = a valid date and time in iso format https://en.wikipedia.org/wiki/ISO_8601
download_url, project_url = required valid url
license = optional string
tags = array of strings
```
This was my discovery. Please define others if i missed any.

**Comment by willwade** [comment]
date: Will be created by backend (or if in the the original format then fine - will read that)

**Comment by hosseinzoda** [comment]
Implemented

**Comment by willwade** [comment]
Great. Thanks for this. Just for documentation - can you point me in the direction where the schema is set?

**Comment by hosseinzoda** [comment]
Here. https://github.com/openassistive/OpenATBackend/commit/1202c41#diff-af81eb01f45a800449706ef402645e6aR10
