### ISSUE TITLE
Need Dropbox service

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#4]
Send a Dropbox URL. If contents of file a openat.md then deal with it.

**Comment by hosseinzoda** [comment]
@willwade Can you send me an example of dropbox project?

**Comment by willwade** [comment]
I think this is very similar if not the same as the http service: https://dl.dropboxusercontent.com/u/66960/Temp/Headpointer/Readme.md

**Comment by willwade** [comment]
Re: issue #2 I think it's the same service given my example above.

**Comment by hosseinzoda** [comment]
I'm assuming https://dl.dropboxusercontent.com/u/66960/Temp/Headpointer/Readme.md is a temp url.

From my point of view difference between this issue and #2 is. When user enters dropbox project url. for example https://www.dropbox.com/sh/0eagft7ugo3xkz0/AAC_WJHVssyY3yMiVgv3aVq-a?dl=0  , A scraper search for a file in there named `openat.md` or `Readme.md` and fetches the data for submit.

And httpfile service skips the above step. I does parse an `.md` file for next step.

@willwade What do you think?

**Comment by willwade** [comment]
I guess you are right actually. So similar but yes - a scrape may be needed. I don't fully understand Dropbox - that URL isn't temporary - well its the one created by "Share this file".

**Comment by hosseinzoda** [comment]
@willwade 
> I don't fully understand Dropbox - that URL isn't temporary - well its the one created by "Share this file".

I  did say that because i saw `Temp` in the url. https://dl.dropboxusercontent.com/u/66960/Temp/Headpointer/Readme.md

**Comment by hosseinzoda** [comment]
Anyway having scraper might be better solution. otherwise i think it's the same as httpfile.

**Comment by willwade** [comment]
Ahh - no. Thats just the folder its currently sitting in in my dropbox. Its just a demo for the purpose of this project. 

But yes - a scraper maybe better - If you do put in the direct "readme.md" link - then yes - the htttpfile service will pick it up... cool

**Comment by hosseinzoda** [comment]
Implemented as a helper to delegate the task httpfile service

Tested with these
```
https://www.dropbox.com/sh/0eagft7ugo3xkz0/AAD_9prg7LW7xZDS05RGtaKKa/Readme.md?dl=0
https://www.dropbox.com/sh/0eagft7ugo3xkz0/AAC_WJHVssyY3yMiVgv3aVq-a
```
