### ISSUE TITLE
service to cache all items locally. 

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#7]
A service (/createIndexCache) that grabs all /items/*.md

Creates a file locally that is a Json file storing:
short_title, URL

Will be run on a webhook when frontend deployed 

(ref: https://github.com/openassistive/OpenATFrontEnd/issues/5)

**Comment by hosseinzoda** [comment]
Since #8 has implemented. I don't think we need this feature. At least util it's working smoothly.

**Comment by willwade** [comment]
yep. closing for now

**Comment by hosseinzoda** [comment]
finished at #15
