### ISSUE TITLE
edit: /service call to check for duplicate

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATBackend#8]
On /service/ call check to see if either URL or short_title in index. If it is carry on but warn user duplicate exists - and provide link to file.

(NB: We will need to make an edit service in the future to edit the short_title.md instead of the scraped version on add)

**Comment by willwade** [comment]
ref: https://github.com/openassistive/OpenATFrontEnd/issues/5

**Comment by hosseinzoda** [comment]
Implemented, not tested
It's going to add `exists` and `current_url` when get from services has `short_title`.

**Comment by willwade** [comment]
Great. To check should the error message: "A duplicate record exists with this short title" actually be "A duplicate record exists with this short title or url" ? I.e. its checking the short title and the URL right?
